services:
  redis:
      image: "redis:alpine"
      ports:
        - "6379:6379"
  django:
    build:
      context: ./TestTaskDjango
      dockerfile: DockerFile.django
    command: >
      sh -c "python manage.py migrate &&
             python manage.py shell < TestTaskDjango/initsuperuser.py &&
             celery -A TestTaskDjango worker --loglevel=info --uid=nobody &
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./TestTaskDjango:/code
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your_secret_key
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173,http://localhost:8080,http://127.0.0.1:8080
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=admin
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
    - redis
  vue:
    build:
      context: ./TestTaskVue
      dockerfile: DockerFile.vuejs
    command: npm run dev -- --host
    volumes:
      - ./TestTaskVue:/app
      - /app/node_modules
    ports:
      - "8080:5173"
    environment:
      - NODE_ENV=development
  django_test:
    build:
      context: ./TestTaskDjango
      dockerfile: DockerFile.django
    command: python manage.py test
    volumes:
      - ./TestTaskDjango:/code
    environment:
      - SECRET_KEY=your_secret_key
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173,http://localhost:8080,http://127.0.0.1:8080
    profiles:
      - test