services:
  django:
    build:
      context: ./TestTaskDjango
      dockerfile: DockerFile.django
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py shell < TestTaskDjango/initsuperuser.py &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./TestTaskDjango:/code
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your_secret_key
      - DEBUG=True
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=admin
  vue:
    build:
      context: ./TestTaskVue
      dockerfile: DockerFile.vuejs
    command: npm run dev -- --host
    volumes:
      - ./TestTaskVue:/app
      - /app/node_modules
    ports:
      - "8080:5173"
    environment:
      - NODE_ENV=development
  django_test:
    build:
      context: ./TestTaskDjango
      dockerfile: DockerFile.django
    command: pytest
    volumes:
      - ./TestTaskDjango:/code
    environment:
      - SECRET_KEY=your_secret_key
      - DEBUG=True
    profiles:
      - test