# Generated by Django 4.2.11 on 2024-05-21 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestTask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s-]+$', 'Enter a valid organization name. Only letters, spaces,and hyphens are allowed.', code='invalid_organization_name')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s-]+$', 'Enter a valid first name. Only letters, spaces,and hyphens are allowed.', code='invalid_first_name')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s-]+$', 'Enter a valid last name. Only letters, spaces,and hyphens are allowed.', code='invalid_last_name')]),
        ),
    ]
